### PR TITLE
Added nodeSelector value to helm chart

### PR DESCRIPTION
**Pull request by Khaos66**
Adds a `nodeSelector` value to the chart for mixed clusters with `linux` and `windows` nodes

Adresses #87

### CODE REVIEW

**Comment by Khaos66** [comment]
Normally I would have increated the `version` in `chart.yaml`
But it looks like it's in sync with the `appVersion`. So I didn't...

**Comment by djkormo** [comment]
Goodf work!. Please change chart version to 2.1.1

**Comment by Khaos66** [comment]
@djkormo I changed the versions

**Comment by jamallorock** [comment]
Looks good. Approved.

**Review by jamallorock — APPROVED** [review]

**Pull request merged**
