### PR TITLE
Fix drop ALL container capabilities

### PR DESCRIPTION
**Pull request by pstefka**
Dropped capabilities need to be uppercase = fixed

### CODE REVIEW

**Comment by djkormo** [comment]
Thanks, I'll check it.

**Comment by pstefka** [comment]
Cześć @djkormo, any chance you had time to check the changed line?

**Comment by djkormo** [comment]
I'm a busy man. Gimme me  few days.

**Comment by djkormo** [comment]
Corrected in https://github.com/djkormo/adcs-issuer/pull/96

Thank you for this fix.

**Pull request closed without merging**
